### ISSUE TITLE
Plugin needs logo and banner assets for wp.org

### ISSUE THREAD

**Issue by ianmjones** [deliciousbrains/spinupwp-plugin#13]
What, no branding?

<img width="1258" alt="Screenshot 2019-06-05 at 19 45 39" src="https://user-images.githubusercontent.com/4710/58981814-06943d80-87cb-11e9-967f-1d86776210af.png">

**Comment by gilbitron** [comment]
@ianmjones The plugin hasn't officially launched yet. Although this is something that needs done @lizDB @lewis-dbi.

**Comment by lizDB** [comment]
@lewis-dbi I believe @A5hleyRich is trying to launch this this week. Any chance you can fit this one in before then? As far as dimensions/what's needed, here's what we did for OSES: https://drive.google.com/drive/folders/128QFtiEwQTr-R39zdXxjWeLmzUARUnli

**Comment by A5hleyRich** [comment]
The wp.org guidelines are here also:

https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons

**Comment by lewis-dbi** [comment]
@lizDB @A5hleyRich  No problem. Will do this at some point today

**Comment by lewis-dbi** [comment]
@lizDB @A5hleyRich 

Here you go folks: https://drive.google.com/drive/folders/16aqRxS05aLDAb3V6Ai1DZ6iDYuVndB6o?usp=sharing

**Comment by lizDB** [comment]
thanks Lewis! Looks good to me. @bradt did you want to sign off on these?

**Comment by bradt** [comment]
@lewis-dbi Can you do a mockup of what it will look like on WP.org please? Hard to visualize.

**Comment by lewis-dbi** [comment]
@bradt @lizDB This morning I mocked up a  couple of different options too.

![v1](https://user-images.githubusercontent.com/48517901/60884196-3f995500-a244-11e9-95c9-ac3133d1472e.jpg)
![v2](https://user-images.githubusercontent.com/48517901/60884198-3f995500-a244-11e9-9b10-ca79b9b55ace.jpg)
![v3](https://user-images.githubusercontent.com/48517901/60884197-3f995500-a244-11e9-8d67-f4434795ea7e.jpg)

**Comment by bradt** [comment]
Hmm, very interesting. Instead of duplicating our branding in the top banner, what if we made the whole top banner a screenshot of the dashboard?

We are going to need screenshots for the listing as well, but since they're at the bottom of the page I was thinking it might be good as the banner too.

**Comment by lewis-dbi** [comment]
@bradt This is the best I can come up with due to the letterbox size of the image.

![v4](https://user-images.githubusercontent.com/48517901/60897049-45e8fa80-a25f-11e9-825e-75fda1cc5ff2.jpg)

Does it matter what the dummy content is? 

Also, it would be good to get a list of what we want to showcase in the screenshots.

**Comment by bradt** [comment]
> Does it matter what the dummy content is?

Yes, I think it does matter. Having spinupwp.com and deliciousbrains.com in there is too meta and will be confusing to potential customers. The dummy content should be something plausible. Ideally something that our customers can relate to and similar to what they might have in their SpinupWP account if they were to sign up. You should check out Iain's SpinupWP video for examples.

**Comment by lewis-dbi** [comment]
@bradt I checked the video and there was only acmepublishing. Shall I use this and another fictional name, or is this still too meta? If so, could you suggest another server name? Thanks.

**Comment by bradt** [comment]
The video has planet names for the servers as well as using acmepublishing for the site name. Another example is Iain's recent OSES screenshots using a plausible store of Norse merchandise: https://staging.deliciousbrains.com/wp-offload-ses/

**Comment by lewis-dbi** [comment]
@bradt Hows this? or a little too much?

![v4](https://user-images.githubusercontent.com/48517901/61122227-1e7d7200-a499-11e9-9389-e45cbfe0a52e.jpg)

**Comment by bradt** [comment]
Nice one 👍

**Comment by A5hleyRich** [comment]
Awesome. If I can get a copy of the assets @lewis-dbi I can release the plugin today.

**Comment by lewis-dbi** [comment]
@A5hleyRich Updated: https://drive.google.com/drive/folders/16aqRxS05aLDAb3V6Ai1DZ6iDYuVndB6o?usp=sharing
