### ISSUE TITLE
Add logo as the admin bar menu item at smaller screensizes

### ISSUE THREAD

**Issue by polevaultweb** [deliciousbrains/spinupwp-plugin#20]
The 'SpinupWP' menu item disappears at 782px and below. We should make sure it shows but as the logo instead (like Yoast)

http://g.recordit.co/jYDqS0RNif.gif

**Comment by A5hleyRich** [comment]
We now show a more whitelabel friendly dashicon on mobile:

<img width="696" alt="Screenshot 2021-01-06 at 12 28 52" src="https://user-images.githubusercontent.com/1422996/103768692-e10c8d00-501a-11eb-8ee0-dfc9eff3ea05.png">
