### ISSUE TITLE
UTM tags

### ISSUE THREAD

**Issue by A5hleyRich** [deliciousbrains/spinupwp-plugin#3]
@lizDB what UTM tags do you want including in the SpinupWP plugin? We only have the following link so far:

<img width="1920" alt="Screenshot 2019-04-22 at 13 48 38" src="https://user-images.githubusercontent.com/1422996/56501081-64afde80-6505-11e9-8a40-71288c579a2a.png">

Links to: https://spinupwp.com/doc/setting-up-transactional-email-wordpress/

**Comment by lizDB** [comment]
Here you go:

https://spinupwp.com/doc/setting-up-transactional-email-wordpress/?utm_campaign=support%2Bdocs&utm_source=SpinupWP%2BMU&utm_medium=insideplugin

If we add any that are calls to action to sign up, I might give you others, but that should work for any doc links.

**Comment by A5hleyRich** [comment]
Resolved in cb96351
