### ISSUE TITLE
Add action for purging of cache so it can be scheduled by WP Cron

### ISSUE THREAD

**Issue by polevaultweb** [deliciousbrains/spinupwp-plugin#30]
Add something like `add_action( 'spinupwp_purge_site_cache', 'spinupwp_purge_site' );`

So then users can do `wp cron event schedule spinupwp_purge_site_cache`

**Comment by therajumandapati** [comment]
This would be great so we can purge cache after deployments using WP CLI

**Comment by A5hleyRich** [comment]
@therajumandapati that's already possible. Check out the docs here:

https://spinupwp.com/doc/cache-daemon/

**Comment by therajumandapati** [comment]
Thank you Ashley.

Thanks,
Raju

**Comment by A5hleyRich** [comment]
Resolved in 7be6fcd
