### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by polevaultweb** [deliciousbrains/spinupwp-plugin#5]

**Comment by polevaultweb** [comment]
Difficult to add review without PR:

- [ ] WP_Post in docblocks should be \WP_Post
- [ ] Add filter on return value of `should_purge_post_status` method with both status params

**Comment by polevaultweb** [comment]
@A5hleyRich ^

**Comment by A5hleyRich** [comment]
Cheers @polevaultweb
