### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by actionTurtle** [deliciousbrains/spinupwp-plugin#52]
Would be great if by default nginx was configure to return content security policy http header

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by katelynnbarlowe** [comment]
@actionTurtle As this relates to the SpinupWP app instead of this particular plugin, I'm moving this request to our internal request tracker. Thank you so much for your feedback! We always appreciate it.
